name: test-format-analyze

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  sidebarx:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "12.x"
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: dart format --set-exit-if-changed lib/

      - name: Analyze
        run: flutter analyze --fatal-warnings lib/

      # - name: Run tests
      #   run: flutter test --no-pub --coverage
